### ISSUE TITLE
dbValue: Support SomeInteger instead of int|int32|int64|uint

### ISSUE THREAD

**Issue by moigagoo** [xzfc/ndb.nim#8]
Is there any reason only int|int32|int64|uint can be wrapped in DbValue? Why not just support SomeInteger (and SomeFloat, too)?

https://github.com/xzfc/ndb.nim/blob/master/ndb/sqlite.nim#L188

**Comment by xzfc** [comment]
> Why not just support SomeInteger (and SomeFloat, too)?

Makes sense.

**Comment by xzfc** [comment]
I thought about this in more detail.

SQLite integers are signed ints up to 64 bit wide, so `high(uint64)` wouldn't fit. https://www.sqlite.org/draft/datatype3.html

So, the options are:
1. Use `SomeInteger` and throw `RangeError` if conversion fails (default when using `v.int64`).
2. Use `int64` only — safe but requires explicit conversion.
3. Use `int | int8 | int16 | int32 | int64 | uint8 | uint16 | uint32` (note no `uint` nor `uint64`).
   If a user wants an exception or overflow, they can call `int64()`/`cast[int64]()` explicitly.

I think option 3 is most appropriate. 

Also, slightly related: nim itself discriminates 64-bit uints for some implementation reasons. https://nim-lang.org/docs/system.html#Ordinal

As for float, we can use `SomeFloat` here, since SQLite floats are 64-bit wide and `float32` fits in `float64`.
